### ISSUE TITLE
Project setup

### ISSUE THREAD

**Issue by omar-muhamad** [Omar-Muhamad/Space-Xplore#25]
This is the project our [link](https://github.com/Omar-Muhamad/Space-Xplore/projects/2).
we are a group of two @gemmen29  and @Omar-Muhamad.

**Comment by elyor-doniyorov** [comment]
Hi @Omar-Muhamad and @gemmen29, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
